In [1]:
import random
import numpy as np
import torch

In [6]:
a = torch.tensor([0, 1, 1, 0, 0])

In [7]:
b = a[0]
print(b, type(b))

tensor(0) <class 'torch.Tensor'>


In [8]:
c = a[0].item()

In [9]:
print(c, type(c))

0 <class 'int'>


In [10]:
controlled_crosswalks_dict = {0: [':9687187500_c0', ':9687187501_c0'], 
                                           1: [':9727816850_c0'],  
                                           2: [':9727816623_c0'],
                                            3: [':9740157155_c0'], 
                                            4: [':cluster_9740157181_9740483933_c0'], 
                                            5: [':9740157194_c0'],  
                                            6: [':9740157209_c0'], 
                                            7: [':9740484527_c0'],
                                            8: [':cluster_172228408_9739966907_9739966910_c2']}

In [13]:
total = len(controlled_crosswalks_dict)
total

9

In [14]:
np.random.randint(2, size=len(controlled_crosswalks_dict))

array([0, 0, 1, 1, 1, 1, 0, 1, 1])

In [15]:
initial_action = [0] + np.random.randint(2, size=len(controlled_crosswalks_dict)).tolist()

In [16]:
initial_action

[0, 1, 1, 0, 1, 0, 0, 0, 1, 0]

In [17]:
torch.tensor(initial_action)

tensor([0, 1, 1, 0, 1, 0, 0, 0, 1, 0])

In [17]:

controlled_crosswalks_dict = {0: [':9687187500_c0', ':9687187501_c0'], 
                                           1: [':9727816850_c0'],  
                                           2: [':9727816623_c0'],
                                            3: [':9740157155_c0'], 
                                            4: [':cluster_9740157181_9740483933_c0'], 
                                            5: [':9740157194_c0'],  
                                            6: [':9740157209_c0'], 
                                            7: [':9740484527_c0'],
                                            8: [':cluster_172228408_9739966907_9739966910_c2']}

initial_action = torch.tensor([0] + np.random.randint(2, size=len(controlled_crosswalks_dict)).tolist())
print(initial_action)

crosswalks_to_disable = initial_action[1:].tolist()
selected_crosswalks = [] 
for i in range(len(crosswalks_to_disable)):
    if crosswalks_to_disable[i] == 1:
        selected_crosswalks.append(controlled_crosswalks_dict[i])

print(selected_crosswalks)

tensor([0, 1, 1, 0, 0, 1, 0, 0, 0, 1])
[[':9687187500_c0', ':9687187501_c0'], [':9727816850_c0'], [':cluster_9740157181_9740483933_c0'], [':cluster_172228408_9739966907_9739966910_c2']]


In [18]:
selected_crosswalks = [crosswalk for i, crosswalks in enumerate(controlled_crosswalks_dict.values()) if initial_action[i+1] == 1 for crosswalk in crosswalks]

In [19]:
selected_crosswalks

[':9687187500_c0',
 ':9687187501_c0',
 ':9727816850_c0',
 ':cluster_9740157181_9740483933_c0',
 ':cluster_172228408_9739966907_9739966910_c2']

In [3]:
controlled_crosswalks_dict = {
            0: {
                'ids': [':9687187500_c0', ':9687187501_c0'],
                'walking_areas': [':9687187501_w1',':9687187501_w0',':9687187500_w1',':9687187500_w0'],
                'connected_areas': ['1058666192','1054121747#1','1054121747#2',':9687187495_w0'], # Add _0 to make it a lane
                'related_junctions': ['9687187500', '9687187501', '9727816658', '9687187495'],
            },
            1: {
                'ids': [':9727816850_c0'],
                'walking_areas': [':9727816850_w0',':9727816850_w1'],
                'connected_areas': [':9727816844_w0', '1058666207#1'], # If it has a w0 its more walking area
                'related_junctions': ['9727816844', '9727816850', '9727816850'],
            },
            2: {
                'ids': [':9727816623_c0'],
                'walking_areas': [':9727816623_w1',':9727816623_w0'],
                'connected_areas': ['1058666188#1', '1051865729#3_0'],
                'related_junctions': ['9727816623'],
            },
            3: {
                'ids': [':9740157155_c0'],
                'walking_areas': [':9740157155_w1', ':9740157155_w0'],
                'connected_areas': ['1060131391#1', ':9740157153_w0'],
                'related_junctions': ['9740157155', '9740157153'],
            },
            4: {
                'ids': [':cluster_9740157181_9740483933_c0'],
                'walking_areas': [':cluster_9740157181_9740483933_w0', ':cluster_9740157181_9740483933_w1'],
                'connected_areas': ['1060131401#3', ':9740157180_w0'],
                'related_junctions': ['cluster_9740157181_9740483933'],
            },
            5: {
                'ids': [':9740157194_c0'],
                'walking_areas': [':9740157194_w1', ':9740157194_w0'],
                'connected_areas': [':9740157192_w0', '1060131406', '1060131405#1'],
                'related_junctions': ['9740157194', '9740157192'],
            },
            6: {
                'ids': [':9740157209_c0'],
                'walking_areas': [':9740157209_w0', ':9740157209_w1'],
                'connected_areas': ['1060131408#1', ':9740157207_w0'],
                'related_junctions': ['9740157209', '9740157207', '9740157211'],
            },
            7: {
                'ids': [':9740484527_c0'],
                'walking_areas': [':9740484527_w0', ':9740484527_w1'],
                'connected_areas': ['1050677005#21', '1060166260#1'],
                'related_junctions': ['9740484527'],
            },
            8: {
                'ids': [':cluster_172228408_9739966907_9739966910_c2'],
                'walking_areas': [':cluster_172228408_9739966907_9739966910_w2', ':cluster_172228408_9739966907_9739966910_w3'],
                'connected_areas': [':9739966908_w0'],
                'related_junctions': [], # This is already in a junction
            }
        }

In [8]:
selected = [':cluster_172228408_9739966907_9739966910_c2']
for crosswalk_id in selected: 
    walking = controlled_crosswalks_dict[next(i for i, d in controlled_crosswalks_dict.items() if crosswalk_id in d['ids'])]['walking_areas']
print(walking)



[':cluster_172228408_9739966907_9739966910_w2', ':cluster_172228408_9739966907_9739966910_w3']


In [11]:
selected = [':9740157209_c0']
for crosswalk_id in selected: 
    connected = controlled_crosswalks_dict[next(i for i, d in controlled_crosswalks_dict.items() if crosswalk_id in d['ids'])]['connected_areas']
print(connected)


['1060131408#1', ':9740157207_w0']
